# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      env:
         SUPER_SECRET: ${{ secrets.SuperSecret }}


    # Runs a single command using the runners shell
    - name: add credentials
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
    - name: echo
      run: echo ${{github.repository}}
    - name: git clone
      run: |
        git submodule add https://github.com/yasmin-aumeeruddy/action-test.git
    - name: Run conversion tool
      run: |
        cd action-test
        git add .
        git init
        rm README.md
        javac GuideConverter.java
        java GuideConverter ${{github.repository}}
        cat README.md
        ls
    - name: commit 
      run: git commit -m "test" 
    - name: git push
      run: git push
    env:
      # This is necessary in order to push a commit to the repo
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
